const MyHomeActionTypes = {
    CHANGE_MYHOME: "CHANGE_MYHOME",
    FILTER_COUNTRIES: "FILTER_COUNTRIES",
    TOGGLE_MYHOME: "TOGGLE_MYHOME",
    TOGGLE_BACKGROUND_HOME: "TOGGLE_BACKGROUND_HOME",
    CHANGE_COUNTRY: "CHANGE_COUNTRY",
};

export default MyHomeActionTypes;
